version: 0.0
os: linux
files:
  - source: /
    destination: /webapps/app
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 180
  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 180
  ValidateService:
    - location: deploy/validate_service.sh
      timeout: 180