version: 0.2

environment_variables:
  plaintext:
    PACKAGE: "github.com/bentekkie/bentekkie-mainframe"
    GODIR: "/go"

phases:
  install:
    runtime-versions:
      golang: 1.12
      nodejs: 10
    commands:
      - cd client && npm install
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GODIR

      - echo Create dir in GOPATH for sources
      - mkdir -p ${GODIR}/src/${PACKAGE}

      - echo Copy source files into GOPATH
      - echo cp -a ${CODEBUILD_SRC_DIR}/.  ${GODIR}/src/${PACKAGE}
      - cp -a ${CODEBUILD_SRC_DIR}/.  ${GODIR}/src/${PACKAGE}

      - cd ${GODIR}/src/${PACKAGE} && go get ./...
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/client && npm run build
      - cd ${GODIR}/src/${PACKAGE} && go build -o ${CODEBUILD_SRC_DIR}/application

artifacts:
  files:
    - client/build/**/*
    - .ebextensions/**/*
    - application
