version: 0.2

environment_variables:
  plaintext:
    PACKAGE: "github.com/bentekkie/bentekkie-mainframe"

phases:
  install:
    runtime-versions:
      golang: 1.12
      nodejs: 10
    commands:
      - cd client && npm install
      - go get ./...
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/client && npm run build
      - go build -o ${CODEBUILD_SRC_DIR}/serverbin

artifacts:
  files:
    - client/build/**/*
    - .ebextensions/**/*
    - .elasticbeanstalk/**/*
    - .settings/**/*
    - commands/**/*
    - raw/**/*
    - routes/**/*
    - views/**/*
    - autocomp/**/*
    - serverbin
    - '*'
