version: "3"
services:
  server:
    image: ghcr.io/bentekkie/bentekkie-mainframe
    ports:
      - 8082:8082
    links:
      - postgresProd
    depends_on: 
      - postgresProd
    env_file: 
      - 'prod.env'
    restart: always
  postgresProd:
    image: postgres:16-alpine
    env_file: 
      - 'prod.env'
    volumes:
      - my_dbdata_prod:/var/lib/postgresql/data
    restart: always
  adminer:
    image: adminer
    restart: always
    links:
      - postgresProd
    depends_on:
      - postgresProd
    ports:
      - 8085:8080
volumes: 
  my_dbdata_prod:
