version: "3"
services:
  postgres:
    image: postgres
    env_file: 
      - .env
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata_test:/var/lib/postgresql/data
volumes: 
  my_dbdata_test:
