// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.7
// source: proto/command/v1/command.proto

package commandv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_ls              CommandType = 0
	CommandType_cat             CommandType = 1
	CommandType_cd              CommandType = 2
	CommandType_help            CommandType = 3
	CommandType_clear           CommandType = 4
	CommandType_landing         CommandType = 5
	CommandType_download_resume CommandType = 6
	CommandType_login           CommandType = 7
	CommandType_exec            CommandType = 8
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "ls",
		1: "cat",
		2: "cd",
		3: "help",
		4: "clear",
		5: "landing",
		6: "download_resume",
		7: "login",
		8: "exec",
	}
	CommandType_value = map[string]int32{
		"ls":              0,
		"cat":             1,
		"cd":              2,
		"help":            3,
		"clear":           4,
		"landing":         5,
		"download_resume": 6,
		"login":           7,
		"exec":            8,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_command_v1_command_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_command_v1_command_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_command_v1_command_proto_rawDescGZIP(), []int{0}
}

type SudoCommandType int32

const (
	SudoCommandType_logout  SudoCommandType = 0
	SudoCommandType_touch   SudoCommandType = 1
	SudoCommandType_mkdir   SudoCommandType = 2
	SudoCommandType_rm      SudoCommandType = 3
	SudoCommandType_adduser SudoCommandType = 4
	SudoCommandType_edit    SudoCommandType = 5
	SudoCommandType_seed    SudoCommandType = 6
	SudoCommandType_dump    SudoCommandType = 7
)

// Enum value maps for SudoCommandType.
var (
	SudoCommandType_name = map[int32]string{
		0: "logout",
		1: "touch",
		2: "mkdir",
		3: "rm",
		4: "adduser",
		5: "edit",
		6: "seed",
		7: "dump",
	}
	SudoCommandType_value = map[string]int32{
		"logout":  0,
		"touch":   1,
		"mkdir":   2,
		"rm":      3,
		"adduser": 4,
		"edit":    5,
		"seed":    6,
		"dump":    7,
	}
)

func (x SudoCommandType) Enum() *SudoCommandType {
	p := new(SudoCommandType)
	*p = x
	return p
}

func (x SudoCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SudoCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_command_v1_command_proto_enumTypes[1].Descriptor()
}

func (SudoCommandType) Type() protoreflect.EnumType {
	return &file_proto_command_v1_command_proto_enumTypes[1]
}

func (x SudoCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SudoCommandType.Descriptor instead.
func (SudoCommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_command_v1_command_proto_rawDescGZIP(), []int{1}
}

type ResponseType int32

const (
	ResponseType_text     ResponseType = 0
	ResponseType_markdown ResponseType = 1
	ResponseType_html     ResponseType = 2
	ResponseType_json     ResponseType = 3
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "text",
		1: "markdown",
		2: "html",
		3: "json",
	}
	ResponseType_value = map[string]int32{
		"text":     0,
		"markdown": 1,
		"html":     2,
		"json":     3,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_command_v1_command_proto_enumTypes[2].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_proto_command_v1_command_proto_enumTypes[2]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_proto_command_v1_command_proto_rawDescGZIP(), []int{2}
}

type AutoCompResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Completions []string `protobuf:"bytes,1,rep,name=completions,proto3" json:"completions,omitempty"`
}

func (x *AutoCompResponse) Reset() {
	*x = AutoCompResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_command_v1_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoCompResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoCompResponse) ProtoMessage() {}

func (x *AutoCompResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_v1_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoCompResponse.ProtoReflect.Descriptor instead.
func (*AutoCompResponse) Descriptor() ([]byte, []int) {
	return file_proto_command_v1_command_proto_rawDescGZIP(), []int{0}
}

func (x *AutoCompResponse) GetCompletions() []string {
	if x != nil {
		return x.Completions
	}
	return nil
}

type Folder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *Folder) Reset() {
	*x = Folder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_command_v1_command_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_v1_command_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_proto_command_v1_command_proto_rawDescGZIP(), []int{1}
}

func (x *Folder) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SudoCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command    SudoCommandType `protobuf:"varint,1,opt,name=command,proto3,enum=mainframe.SudoCommandType" json:"command,omitempty"`
	Args       []string        `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	CurrentDir *Folder         `protobuf:"bytes,3,opt,name=currentDir,proto3" json:"currentDir,omitempty"`
	Jwt        string          `protobuf:"bytes,4,opt,name=jwt,proto3" json:"jwt,omitempty"`
}

func (x *SudoCommand) Reset() {
	*x = SudoCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_command_v1_command_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SudoCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SudoCommand) ProtoMessage() {}

func (x *SudoCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_v1_command_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SudoCommand.ProtoReflect.Descriptor instead.
func (*SudoCommand) Descriptor() ([]byte, []int) {
	return file_proto_command_v1_command_proto_rawDescGZIP(), []int{2}
}

func (x *SudoCommand) GetCommand() SudoCommandType {
	if x != nil {
		return x.Command
	}
	return SudoCommandType_logout
}

func (x *SudoCommand) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *SudoCommand) GetCurrentDir() *Folder {
	if x != nil {
		return x.CurrentDir
	}
	return nil
}

func (x *SudoCommand) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command    CommandType `protobuf:"varint,1,opt,name=command,proto3,enum=mainframe.CommandType" json:"command,omitempty"`
	Args       []string    `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	CurrentDir *Folder     `protobuf:"bytes,3,opt,name=currentDir,proto3" json:"currentDir,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_command_v1_command_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_v1_command_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_command_v1_command_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetCommand() CommandType {
	if x != nil {
		return x.Command
	}
	return CommandType_ls
}

func (x *Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetCurrentDir() *Folder {
	if x != nil {
		return x.CurrentDir
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command    *Command     `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	CurrentDir *Folder      `protobuf:"bytes,2,opt,name=currentDir,proto3" json:"currentDir,omitempty"`
	Resp       string       `protobuf:"bytes,3,opt,name=resp,proto3" json:"resp,omitempty"`
	Type       ResponseType `protobuf:"varint,4,opt,name=type,proto3,enum=mainframe.ResponseType" json:"type,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_command_v1_command_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_v1_command_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_command_v1_command_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Response) GetCurrentDir() *Folder {
	if x != nil {
		return x.CurrentDir
	}
	return nil
}

func (x *Response) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

func (x *Response) GetType() ResponseType {
	if x != nil {
		return x.Type
	}
	return ResponseType_text
}

type SudoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command    *SudoCommand `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	CurrentDir *Folder      `protobuf:"bytes,2,opt,name=currentDir,proto3" json:"currentDir,omitempty"`
	Resp       string       `protobuf:"bytes,3,opt,name=resp,proto3" json:"resp,omitempty"`
	Type       ResponseType `protobuf:"varint,4,opt,name=type,proto3,enum=mainframe.ResponseType" json:"type,omitempty"`
}

func (x *SudoResponse) Reset() {
	*x = SudoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_command_v1_command_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SudoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SudoResponse) ProtoMessage() {}

func (x *SudoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_v1_command_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SudoResponse.ProtoReflect.Descriptor instead.
func (*SudoResponse) Descriptor() ([]byte, []int) {
	return file_proto_command_v1_command_proto_rawDescGZIP(), []int{5}
}

func (x *SudoResponse) GetCommand() *SudoCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SudoResponse) GetCurrentDir() *Folder {
	if x != nil {
		return x.CurrentDir
	}
	return nil
}

func (x *SudoResponse) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

func (x *SudoResponse) GetType() ResponseType {
	if x != nil {
		return x.Type
	}
	return ResponseType_text
}

var File_proto_command_v1_command_proto protoreflect.FileDescriptor

var file_proto_command_v1_command_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x6f,
	0x43, 0x6f, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x1c,
	0x0a, 0x06, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x9c, 0x01, 0x0a,
	0x0b, 0x53, 0x75, 0x64, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x34, 0x0a, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x75, 0x64, 0x6f, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x31, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x44, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x0a, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6a, 0x77, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x77, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x31, 0x0a,
	0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x46, 0x6f,
	0x6c, 0x64, 0x65, 0x72, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x72,
	0x22, 0xac, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x31, 0x0a, 0x0a, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x46, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65,
	0x73, 0x70, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0xb4, 0x01, 0x0a, 0x0c, 0x53, 0x75, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x75,
	0x64, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x31, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x2e, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x44, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x72, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x6c, 0x73, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x63, 0x61, 0x74, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x63, 0x64, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x63, 0x6c, 0x65, 0x61,
	0x72, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x6c, 0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x05,
	0x12, 0x13, 0x0a, 0x0f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x07,
	0x12, 0x08, 0x0a, 0x04, 0x65, 0x78, 0x65, 0x63, 0x10, 0x08, 0x2a, 0x66, 0x0a, 0x0f, 0x53, 0x75,
	0x64, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x74, 0x6f, 0x75,
	0x63, 0x68, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x6d, 0x6b, 0x64, 0x69, 0x72, 0x10, 0x02, 0x12,
	0x06, 0x0a, 0x02, 0x72, 0x6d, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x75, 0x73,
	0x65, 0x72, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x65, 0x64, 0x69, 0x74, 0x10, 0x05, 0x12, 0x08,
	0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x64, 0x75, 0x6d, 0x70,
	0x10, 0x07, 0x2a, 0x3a, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x6d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x68, 0x74,
	0x6d, 0x6c, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x10, 0x03, 0x32, 0xc1,
	0x02, 0x0a, 0x05, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x35, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x13, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x0e, 0x72, 0x75, 0x6e, 0x53, 0x75, 0x64, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x75,
	0x64, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x75, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x1b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x73, 0x75, 0x64, 0x6f, 0x41, 0x75, 0x74, 0x6f, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x2e, 0x53, 0x75, 0x64, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a,
	0x1b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x41, 0x75, 0x74, 0x6f,
	0x43, 0x6f, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x07,
	0x67, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x46, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x65, 0x6e, 0x74, 0x65, 0x6b, 0x6b, 0x69, 0x65, 0x2f, 0x62, 0x65, 0x6e, 0x74, 0x65,
	0x6b, 0x6b, 0x69, 0x65, 0x2d, 0x6d, 0x61, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2f, 0x76, 0x31, 0x3b,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_command_v1_command_proto_rawDescOnce sync.Once
	file_proto_command_v1_command_proto_rawDescData = file_proto_command_v1_command_proto_rawDesc
)

func file_proto_command_v1_command_proto_rawDescGZIP() []byte {
	file_proto_command_v1_command_proto_rawDescOnce.Do(func() {
		file_proto_command_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_command_v1_command_proto_rawDescData)
	})
	return file_proto_command_v1_command_proto_rawDescData
}

var file_proto_command_v1_command_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_command_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_command_v1_command_proto_goTypes = []interface{}{
	(CommandType)(0),         // 0: mainframe.CommandType
	(SudoCommandType)(0),     // 1: mainframe.SudoCommandType
	(ResponseType)(0),        // 2: mainframe.ResponseType
	(*AutoCompResponse)(nil), // 3: mainframe.AutoCompResponse
	(*Folder)(nil),           // 4: mainframe.Folder
	(*SudoCommand)(nil),      // 5: mainframe.SudoCommand
	(*Command)(nil),          // 6: mainframe.Command
	(*Response)(nil),         // 7: mainframe.Response
	(*SudoResponse)(nil),     // 8: mainframe.SudoResponse
	(*emptypb.Empty)(nil),    // 9: google.protobuf.Empty
}
var file_proto_command_v1_command_proto_depIdxs = []int32{
	1,  // 0: mainframe.SudoCommand.command:type_name -> mainframe.SudoCommandType
	4,  // 1: mainframe.SudoCommand.currentDir:type_name -> mainframe.Folder
	0,  // 2: mainframe.Command.command:type_name -> mainframe.CommandType
	4,  // 3: mainframe.Command.currentDir:type_name -> mainframe.Folder
	6,  // 4: mainframe.Response.command:type_name -> mainframe.Command
	4,  // 5: mainframe.Response.currentDir:type_name -> mainframe.Folder
	2,  // 6: mainframe.Response.type:type_name -> mainframe.ResponseType
	5,  // 7: mainframe.SudoResponse.command:type_name -> mainframe.SudoCommand
	4,  // 8: mainframe.SudoResponse.currentDir:type_name -> mainframe.Folder
	2,  // 9: mainframe.SudoResponse.type:type_name -> mainframe.ResponseType
	6,  // 10: mainframe.shell.runCommand:input_type -> mainframe.Command
	5,  // 11: mainframe.shell.runSudoCommand:input_type -> mainframe.SudoCommand
	6,  // 12: mainframe.shell.autoComplete:input_type -> mainframe.Command
	5,  // 13: mainframe.shell.sudoAutoComplete:input_type -> mainframe.SudoCommand
	9,  // 14: mainframe.shell.getRoot:input_type -> google.protobuf.Empty
	7,  // 15: mainframe.shell.runCommand:output_type -> mainframe.Response
	8,  // 16: mainframe.shell.runSudoCommand:output_type -> mainframe.SudoResponse
	3,  // 17: mainframe.shell.autoComplete:output_type -> mainframe.AutoCompResponse
	3,  // 18: mainframe.shell.sudoAutoComplete:output_type -> mainframe.AutoCompResponse
	4,  // 19: mainframe.shell.getRoot:output_type -> mainframe.Folder
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_command_v1_command_proto_init() }
func file_proto_command_v1_command_proto_init() {
	if File_proto_command_v1_command_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_command_v1_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutoCompResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_command_v1_command_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Folder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_command_v1_command_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SudoCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_command_v1_command_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_command_v1_command_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_command_v1_command_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SudoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_command_v1_command_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_command_v1_command_proto_goTypes,
		DependencyIndexes: file_proto_command_v1_command_proto_depIdxs,
		EnumInfos:         file_proto_command_v1_command_proto_enumTypes,
		MessageInfos:      file_proto_command_v1_command_proto_msgTypes,
	}.Build()
	File_proto_command_v1_command_proto = out.File
	file_proto_command_v1_command_proto_rawDesc = nil
	file_proto_command_v1_command_proto_goTypes = nil
	file_proto_command_v1_command_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShellClient is the client API for Shell service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShellClient interface {
	RunCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	RunSudoCommand(ctx context.Context, in *SudoCommand, opts ...grpc.CallOption) (*SudoResponse, error)
	AutoComplete(ctx context.Context, in *Command, opts ...grpc.CallOption) (*AutoCompResponse, error)
	SudoAutoComplete(ctx context.Context, in *SudoCommand, opts ...grpc.CallOption) (*AutoCompResponse, error)
	GetRoot(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Folder, error)
}

type shellClient struct {
	cc grpc.ClientConnInterface
}

func NewShellClient(cc grpc.ClientConnInterface) ShellClient {
	return &shellClient{cc}
}

func (c *shellClient) RunCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/mainframe.shell/runCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shellClient) RunSudoCommand(ctx context.Context, in *SudoCommand, opts ...grpc.CallOption) (*SudoResponse, error) {
	out := new(SudoResponse)
	err := c.cc.Invoke(ctx, "/mainframe.shell/runSudoCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shellClient) AutoComplete(ctx context.Context, in *Command, opts ...grpc.CallOption) (*AutoCompResponse, error) {
	out := new(AutoCompResponse)
	err := c.cc.Invoke(ctx, "/mainframe.shell/autoComplete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shellClient) SudoAutoComplete(ctx context.Context, in *SudoCommand, opts ...grpc.CallOption) (*AutoCompResponse, error) {
	out := new(AutoCompResponse)
	err := c.cc.Invoke(ctx, "/mainframe.shell/sudoAutoComplete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shellClient) GetRoot(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Folder, error) {
	out := new(Folder)
	err := c.cc.Invoke(ctx, "/mainframe.shell/getRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShellServer is the server API for Shell service.
type ShellServer interface {
	RunCommand(context.Context, *Command) (*Response, error)
	RunSudoCommand(context.Context, *SudoCommand) (*SudoResponse, error)
	AutoComplete(context.Context, *Command) (*AutoCompResponse, error)
	SudoAutoComplete(context.Context, *SudoCommand) (*AutoCompResponse, error)
	GetRoot(context.Context, *emptypb.Empty) (*Folder, error)
}

// UnimplementedShellServer can be embedded to have forward compatible implementations.
type UnimplementedShellServer struct {
}

func (*UnimplementedShellServer) RunCommand(context.Context, *Command) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCommand not implemented")
}
func (*UnimplementedShellServer) RunSudoCommand(context.Context, *SudoCommand) (*SudoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSudoCommand not implemented")
}
func (*UnimplementedShellServer) AutoComplete(context.Context, *Command) (*AutoCompResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutoComplete not implemented")
}
func (*UnimplementedShellServer) SudoAutoComplete(context.Context, *SudoCommand) (*AutoCompResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SudoAutoComplete not implemented")
}
func (*UnimplementedShellServer) GetRoot(context.Context, *emptypb.Empty) (*Folder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoot not implemented")
}

func RegisterShellServer(s *grpc.Server, srv ShellServer) {
	s.RegisterService(&_Shell_serviceDesc, srv)
}

func _Shell_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShellServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainframe.shell/RunCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShellServer).RunCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shell_RunSudoCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SudoCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShellServer).RunSudoCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainframe.shell/RunSudoCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShellServer).RunSudoCommand(ctx, req.(*SudoCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shell_AutoComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShellServer).AutoComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainframe.shell/AutoComplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShellServer).AutoComplete(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shell_SudoAutoComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SudoCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShellServer).SudoAutoComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainframe.shell/SudoAutoComplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShellServer).SudoAutoComplete(ctx, req.(*SudoCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shell_GetRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShellServer).GetRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainframe.shell/GetRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShellServer).GetRoot(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shell_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mainframe.shell",
	HandlerType: (*ShellServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "runCommand",
			Handler:    _Shell_RunCommand_Handler,
		},
		{
			MethodName: "runSudoCommand",
			Handler:    _Shell_RunSudoCommand_Handler,
		},
		{
			MethodName: "autoComplete",
			Handler:    _Shell_AutoComplete_Handler,
		},
		{
			MethodName: "sudoAutoComplete",
			Handler:    _Shell_SudoAutoComplete_Handler,
		},
		{
			MethodName: "getRoot",
			Handler:    _Shell_GetRoot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/command/v1/command.proto",
}
