name: Build Image
run-name: Build Image
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
# This gives read-only access to the token.
permissions: read-all

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Log in to the Container registry
              uses: docker/login-action@5d8785b43a795ee002a17dbf1a2235dc1997224b
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Get Bazel
              uses: bazel-contrib/setup-bazel@90b352333885f9fb6bf262d8e659f01b6219cc25 # 0.9.0
              with:
                # Avoid downloading Bazel every time.
                bazelisk-cache: true
                # Store build cache per workflow.
                disk-cache: ${{ github.workflow }}
                # Share repository cache between workflows.
                repository-cache: true
            - name: Build and Push
              run: bazelisk build :bentekkie-mainframe_image_tarball
