name: Build Image
run-name: Build Image
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
# This gives read-only access to the token.
permissions: read-all

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Log in to the Container registry
              uses: docker/login-action@3b8fed7e4b60203b2aa0ecc6c6d6d91d12c06760
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Get Bazel
              uses: bazel-contrib/setup-bazel@e403ad507104847c3539436f64a9e9eecc73eeec # v0.8.5
              with:
                # Avoid downloading Bazel every time.
                bazelisk-cache: true
                # Store build cache per workflow.
                disk-cache: ${{ github.workflow }}
                # Share repository cache between workflows.
                repository-cache: true
            - name: Build and Push
              run: bazelisk build :bentekkie-mainframe_image_tarball
